### PR TITLE
Rebuild pod

### PR DESCRIPTION
**Pull request by tonystone**
This was a rebuild of the Lolay Investigo open-source library to update it to use the current CocoaPod template and update all the dependent libraries to the latest vender versions.  
### Rebuilt CocoaPod
- Restructured pod using current CocoaPod template.
- Changed podspec source Temporarily to the TheClimateCorporation for internal testing.
- Adding umbrella header 'LolayInvestigo.h"
- Added public_header_files to podspec to specific define the public interface.
- Added a module name to specify "LoalyInvestigo" for frameworks.
- Added LolayInvestigo.h to public_header_files and source.
- Replaced the embedded Flurry lib with the latest official Flurry-iOS-SDK ('~>7.0')  CocoaPod.
- Removed the embedded Analytics lib and replace with Segment.ios latest CocoaPod (Analytics/Segmentio, '~> 2.0').
- Removed Analytics/Flurry sub module completely since we're including the official version threw the Flurry CocoaPod.
- Moved all source files into their default CocoaPod location.
- Removed embedded OCMock library and replaced with CocoaPod OCMock.
- Moved all OCMock tests into Example/tests.
- Validated that existing tests run and pass.  8 Tests passed.  Note: the Flurry tests where previously commented out and for now these were left commented out.
- Updated pod version to 2.1.0 to match semantic versioning scheme and increment the number to reflect these changes.
- Validated pod lib with "pod lib lint --use-libraries --allow-warnings". 
### Update LolayFlurryTracker.m
- Temporarily commented out a build error on setPushToken for LolayFlurryTracker.
### Notes

In order to use the Flurry library with "Objective-C" frameworks, you must use the CocoaPods switch "--use-libraries" during pod lint and pod lib push.  This is due to Flurry still shipping a static library.

You also have to use "--allow-warnings" with XCode 7 because segment has 2 warnings in their library.

### CODE REVIEW

**Comment by tchagnon** [comment]
Hi Tony,

The description, umbrella header and podspec files look good to me.  With all the file moves, I didn't review any other files, but I think the description makes sense.  Standard follow-up questions:  Does it pass tests and run / integrate with our existing app?  Did you check with DA team that it's sending events to them, etc?

Do you have permissions to make the merge here or do you need me or Joost to do anything?

Thanks,
Tim

**Comment by tonystone** [comment]
Hi @tchagnon , all good questions.  Yes, reviewing the header and podspec should be sufficient as all the rest was simply moving files around and restructuring the directories.

Follow up questions:
1) Does it pass tests and run - Yes, all the tests that are not commented out, run as expected although there are not many.
2) Integrate with our existing app - I have not integrated with the existing app yet but have integrated with several other libs and several test apps using both frameworks and not.  I will try it out on the basic app and add another comment.
3) Did you check with DA team that it's sending events to them, etc? - No as this does not add anything to our backend, it still just uses Segment to send to segments backend.  The testing with ClimateTracker will happen in a different pod that includes this one.
4) Do you have permissions to make the merge here or do you need me or Joost to do anything? - Yes, I have all the permission I need for the merge, thanks.

**Comment by tchagnon** [comment]
Great, thanks for the answers.  They make sense, I figured there was still some integration work to be done.  It's ok by me if you want to merge at this point.

**Comment by tonystone** [comment]
Thanks for the help @tchagnon , moving forward with the merge.

**Comment by jklimaat** [comment]
@tonystone The changes look good to me, sorry for the delay in reviewing. Based on your discussion with Tim, I feel confident about the merge.

**Pull request merged**
